GET http://localhost:3001/todos


###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text" : "delete me"
}

###

DELETE http://localhost:3001/todo/delete/62ee3c1dd62c072b2be58ce5


###

PUT http://localhost:3001/todo/complete/62ed78b3e7a132697e627b2a
